tasks:
  - name: install-dependencies
    before: |
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      printf 'export PATH="/workspace/ds201-lab03/apache-cassandra-4.1.0/bin:$PATH"' >> $HOME/.bashrc
    init: |
      curl https://dlcdn.apache.org/cassandra/4.1.0/apache-cassandra-4.1.0-bin.tar.gz \
        --output apache-cassandra-4.1.0-bin.tar.gz
      tar xf apache-cassandra-4.1.0-bin.tar.gz
    command: | 
      /workspace/ds201-lab03/apache-cassandra-4.1.0/bin/cassandra
      gp sync-done server-start
  - name: load-data
    init: gp sync-await server start
    command: cqlsh - e "CREATE KEYSPACE killrvideo \
                        WITH replication = { \
                          'class':'SimpleStrategy', \
                          'replication_factor': 1 \
                        };"
github:
  prebuilds:
    main: true
ports:
  - port: 1-9999
    onOpen: ignore
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/1.1.0-beta2/katapod-1.1.0-beta2.vsix
image: gitpod/workspace-full:2023-02-27-14-39-56